CREATE TABLE PRICES (
    PRICE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INTEGER NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRICE_LIST INTEGER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    CONSTRAINT UNIQUE_PRIORITY_PRODUCT_PRICE_LIST UNIQUE (PRIORITY, PRODUCT_ID, PRICE_LIST)
);
